name: Lint Build Test

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . -t ecdemo:0.1
    - name: Test
      run: docker run --rm -it ecdemo:0.1